import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.7.1"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }
  
  try {
    const { fullName, email, mobileNumber, requestedPlan, billingCycle, paidAmount, receiptPath } = await req.json()

    // Create Supabase Admin client using internal env keys
    const supabaseUrl = Deno.env.get('SUPABASE_URL') ?? ''
    const supabaseServiceRoleKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    const supabaseAdmin = createClient(supabaseUrl, supabaseServiceRoleKey)

    // Generate signed URL (604800 seconds = 7 days)
    const { data: signedData, error: signedError } = await supabaseAdmin.storage
      .from('payment-receipts')
      .createSignedUrl(receiptPath, 604800)

    if (signedError) {
      throw new Error(`Failed to generate signed URL: ${signedError.message}`)
    }

    const signedUrl = signedData?.signedUrl

    // Send email via Resend API using the environment variable
    const resendApiKey = Deno.env.get('RESEND_API_KEY')
    if (!resendApiKey) {
      throw new Error('RESEND_API_KEY environment variable is not set')
    }

    const emailResponse = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${resendApiKey}`
      },
      body: JSON.stringify({
        from: 'ReachDesk <onboarding@resend.dev>',
        to: ['dotthedart@gmail.com'],
        subject: `New Upgrade Request — ${fullName} (${requestedPlan})`,
        html: `
          <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; border: 1px solid #ddd; padding: 20px; border-radius: 8px;">
            <h2 style="color: #6d28d9; border-bottom: 2px solid #6d28d9; padding-bottom: 8px;">New Plan Upgrade / Renewal Request</h2>
            <p>A new payment verification request has been submitted by a customer. Please review the details below:</p>
            <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
              <tr>
                <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold; width: 150px;">Full Name:</td>
                <td style="padding: 8px; border-bottom: 1px solid #eee;">${fullName}</td>
              </tr>
              <tr>
                <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Email:</td>
                <td style="padding: 8px; border-bottom: 1px solid #eee;">${email}</td>
              </tr>
              <tr>
                <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Mobile:</td>
                <td style="padding: 8px; border-bottom: 1px solid #eee;">${mobileNumber}</td>
              </tr>
              <tr>
                <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Plan:</td>
                <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold; color: #7c3aed;">${requestedPlan.toUpperCase()}</td>
              </tr>
              <tr>
                <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Billing Cycle:</td>
                <td style="padding: 8px; border-bottom: 1px solid #eee;">${billingCycle.toUpperCase()}</td>
              </tr>
              <tr>
                <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Paid Amount:</td>
                <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold; color: #059669;">Rs ${paidAmount.toLocaleString()}</td>
              </tr>
            </table>
            
            <div style="margin-top: 25px; text-align: center;">
              <a href="${signedUrl}" target="_blank" rel="noopener noreferrer" style="background-color: #6d28d9; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold; display: inline-block; box-shadow: 0 4px 6px rgba(109, 40, 217, 0.2);">
                View Payment Receipt (Valid 7 Days)
              </a>
            </div>
            
            <p style="font-size: 0.8rem; color: #888; margin-top: 30px; border-top: 1px solid #eee; padding-top: 15px;">
              This email notification is auto-generated by the ReachDesk Payment Flow. The attached receipt link will expire in 7 days.
            </p>
          </div>
        `
      })
    })

    if (!emailResponse.ok) {
      const errText = await emailResponse.text()
      throw new Error(`Resend API failed: ${errText}`)
    }

    const resData = await emailResponse.json()

    return new Response(
      JSON.stringify({ success: true, message: 'Email sent successfully', data: resData }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 200 }
    )
  } catch (error) {
    return new Response(
      JSON.stringify({ success: false, error: error.message }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 400 }
    )
  }
})
